-- Script generated by Redgate Compare v1.7.1.7638

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film_category';END$$;
DROP TABLE public.film_category;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film_actor';END$$;
DROP TABLE public.film_actor;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film.film_original_language_id_fkey';END$$;
ALTER TABLE public.film DROP CONSTRAINT film_original_language_id_fkey;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film.film_language_id_fkey';END$$;
ALTER TABLE public.film DROP CONSTRAINT film_language_id_fkey;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.customer.customer_address_id_fkey';END$$;
ALTER TABLE public.customer DROP CONSTRAINT customer_address_id_fkey;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.store_store_id_seq';END$$;
DROP SEQUENCE public.store_store_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.store';END$$;
DROP TABLE public.store;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.staff_staff_id_seq';END$$;
DROP SEQUENCE public.staff_staff_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.staff';END$$;
DROP TABLE public.staff;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.rental_rental_id_seq';END$$;
DROP SEQUENCE public.rental_rental_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.rental';END$$;
DROP TABLE public.rental;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.payment_payment_id_seq';END$$;
DROP SEQUENCE public.payment_payment_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.payment';END$$;
DROP TABLE public.payment;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.language_language_id_seq';END$$;
DROP SEQUENCE public.language_language_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.language';END$$;
DROP TABLE public.language;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.inventory_inventory_id_seq';END$$;
DROP SEQUENCE public.inventory_inventory_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.inventory';END$$;
DROP TABLE public.inventory;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film_film_id_seq';END$$;
DROP SEQUENCE public.film_film_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film';END$$;
DROP TABLE public.film;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.customer_customer_id_seq';END$$;
DROP SEQUENCE public.customer_customer_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.customer';END$$;
DROP TABLE public.customer;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.country_country_id_seq';END$$;
DROP SEQUENCE public.country_country_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.country';END$$;
DROP TABLE public.country;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.city_city_id_seq';END$$;
DROP SEQUENCE public.city_city_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.city';END$$;
DROP TABLE public.city;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.category_category_id_seq';END$$;
DROP SEQUENCE public.category_category_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.category';END$$;
DROP TABLE public.category;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.address_address_id_seq';END$$;
DROP SEQUENCE public.address_address_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.address';END$$;
DROP TABLE public.address;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.actor_actor_id_seq';END$$;
DROP SEQUENCE public.actor_actor_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.actor';END$$;
DROP TABLE public.actor;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.mpaa_rating';END$$;
DROP TYPE public.mpaa_rating;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.year';END$$;
DROP DOMAIN public.year;
SET check_function_bodies = true;
