-- Script generated by Redgate Compare v1.7.1.7638

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.address.address_city_id_fkey';END$$;
ALTER TABLE public.address DROP CONSTRAINT address_city_id_fkey;
SET check_function_bodies = true;
