-- Script generated by Redgate Compare v1.7.1.7638

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.city.city_country_id_fkey';END$$;
ALTER TABLE public.city DROP CONSTRAINT city_country_id_fkey;
SET check_function_bodies = true;
