-- Script generated by Redgate Compare v1.7.1.7638

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public._group_concat(text, text)';END$$;
DROP FUNCTION public._group_concat(text, text);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.rewards_report(integer, numeric)';END$$;
DROP FUNCTION public.rewards_report(integer, numeric);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.last_day(timestamp with time zone)';END$$;
DROP FUNCTION public.last_day(timestamp with time zone);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.inventory_in_stock(integer)';END$$;
DROP FUNCTION public.inventory_in_stock(integer);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.inventory_held_by_customer(integer)';END$$;
DROP FUNCTION public.inventory_held_by_customer(integer);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.get_customer_balance(integer, timestamp with time zone)';END$$;
DROP FUNCTION public.get_customer_balance(integer, timestamp with time zone);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film_not_in_stock(integer, integer)';END$$;
DROP FUNCTION public.film_not_in_stock(integer, integer);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.film_in_stock(integer, integer)';END$$;
DROP FUNCTION public.film_in_stock(integer, integer);
SET check_function_bodies = true;
