-- Script generated by Redgate Compare v1.7.1.7682

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.user_social';END$$;
DROP TABLE public.user_social;
SET check_function_bodies = true;
